server:
  port: 8080
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update

    datasource:
        url: jdbc:mysql://localhost:3306/custer
        username: root
        password: root
        name: custer
        driver-class-name: com.mysql.jdbc.Driver
secret.key : dc6589483a672de25ff765172494d42e138cd8a5
auth.header.name: Token
token.expiration.time: 3